episodes:
  - scene_asset_path: GRUtopia/assets/scenes/grid.usd
    scene_scale: [ 0.25, 0.25, 0.25 ]
    robots:
      - name: h1
        prim_path: "/World/h1"
        type: "HumanoidRobot"
        position: [ .0, .0, 1.05 ]
        scale: [ 1, 1, 1 ]
        controller_params:
          - name: "move_by_speed"
          - name: "joint_controller"
          - name: "move_to_point"
          - name: "move_along_path"
          - name: "rotate"
        sensor_params:
          - name: "camera"
            enable: True
          - name: "tp_camera"
            enable: False
  - scene_asset_path: GRUtopia/assets/scenes/grid.usd
    robots:
      - name: h1
        prim_path: "/World/h1"
        type: "HumanoidRobot"
        position: [ .0, .0, 1.05 ]
        scale: [ 1, 1, 1 ]
        controller_params:
          - name: "move_by_speed"
          - name: "joint_controller"
          - name: "move_to_point"
          - name: "move_along_path"
          - name: "rotate"
        sensor_params:
          - name: "camera"
            enable: True
          - name: "tp_camera"
            enable: False
  - scene_asset_path: GRUtopia/assets/scenes/grid.usd
    robots:
      - name: h1
        prim_path: "/World/h1"
        type: "HumanoidRobot"
        position: [ .0, .0, 1.05 ]
        scale: [ 1, 1, 1 ]
        controller_params:
          - name: "move_by_speed"
          - name: "joint_controller"
          - name: "move_to_point"
          - name: "move_along_path"
          - name: "rotate"
        sensor_params:
          - name: "camera"
            enable: True
          - name: "tp_camera"
            enable: False
