simulator:
  physics_dt: 1/240
  rendering_dt: 1/240
#  rendering_interval: 100

agents:
#- type: NPCAgent
#  agent_config:
#    name: "npc-0"
#    model_name: gpt-4o
#    openai_api_key: "YOUR_OPENAI_API_KEY"
#    scene_data_path: GRUtopia/assets/scenes/demo_house/object_dict_with_caption.json
- type: DummyAgent
  agent_config:
    test: true


task_config:
  type: "SocialBenchmarkTask"
  task_name_prefix: "h1_social_navigation"
  env_num: 1
  offset_size: 10
  metrics:
  - type: SimpleMetric
    metric_config: # custom metric config
      robot_name: h1
  metrics_save_path: console
  task_settings:
    max_step: 2000
    verbose: False
    fall_threshold: 0.3
    max_dialogue: 3
  episodes:
  - scene_asset_path: GRUtopia/assets/scenes/grid.usd
    scene_scale: [1., 1., 1.]
    robots:
    - name: h1
      prim_path: "/World/h1"
      type: "HumanoidRobot"
      position: [ .0, .0, 1.05 ]
      scale: [ 1, 1, 1 ]
      controller_params:
      - name: "move_by_speed"
      - name: "joint_controller"
      - name: "move_to_point"
      - name: "move_along_path"
      - name: "rotate"
      sensor_params:
      - name: "camera"
        enable: True
      - name: "tp_camera"
        enable: False
    meta:
      prompt: "Prompt test 1"
